version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE

  db:
    image: postgres
    restart: always
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=product_command
    ports:
      - "5431:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "psql -h localhost -U postgres -d product_command -c 'SELECT 1;'"
        ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    volumes:
      - ./.docker/db/data:/var/lib/postgresql/:delegated

  product-query-service:
    image: matheusvict/product-query-service:latest
    ports:
      - "8080:8080"
    environment:
      - PG_HOST=db
      - KAFKA_HOST=kafka
    depends_on:
      - db
      - kafka
      - zookeeper
      - product-command-service

  product-command-service:
    image: matheusvict/product-command-service:latest
    ports:
      - "8081:8081"
    environment:
      - PG_HOST=db
      - KAFKA_HOST=kafka
    depends_on:
      - db
      - kafka
      - zookeeper

networks:
  default:
    driver: bridge
    name: spring-rcqrs
