spring:
  application:
    name: product-query-service

  datasource:
  url: jdbc:postgresql://${PG_HOST:localhost}:${PG_PORT:5432}/${PG_DB:product_command}
  username: ${PG_USER:postgres}
  password: ${PG_PASS:123}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_HOST:localhost}:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
server:
  port: 8080
